### ISSUE TITLE
Add support for more languages to this plugin

### ISSUE THREAD

**Issue by Kauo7420** [EricLangezaal/ZombieApocalypse#15]
## Simplified Chinese
```
messages:
   no-command-permission: "§4§l抱歉§r§7，您没有权限执行此操作！"

   # started-success supports placeholder {world_name}
   started-success: "§a世界 '{world_name}' 成功启动了末日！"
   # started-broadcast supports placeholder {world_name}
   started-broadcast: "§d僵尸末日已经开始了！"
   # started-failed supports placeholder {world_name}
   start-failed: "§c'{world_name}' 已经开始了末日"
   # started-failed supports placeholder {input}, for the users faulty duration input
   start-invalid-duration: "§c末日持续时间必须是整数！"

   # ended-success supports placeholder {world_name}
   ended-success: "§a世界 '{world_name}' 的末日已经结束了！"
   # ended-failed supports placeholder {world_name}
   end-failed: "§c'{world_name}' 中没有末日"
   # ended-broadcast supports placeholder {world_name}
   ended-broadcast: "§d这个世界的僵尸末日已经结束了，你现在安全了（暂时）！"
   
   reload-success: "§a插件已成功重新加载！"
   reload-fail: "§c重新加载配置文件失败！请查看控制台以获取更多详细信息。"
   
   mobcap-too-few-arguments: "§c请同时提供世界名称和所需的生物群系上限！"
   # supports placeholder {input} for the invalid user input
   mobcap-invalid-amount: "§c请（也）提供生物群系上限为整数"
   # supports placeholder {world_name}
   mobcap-no-apocalypse: "§7'{world_name}' 中没有 §4僵尸末日§2"
   # supports placeholders {world_name} and {mobcap} for the new mob cap
   mobcap-success: "§a将每个区块的最大僵尸生成数设置为 {mobcap} 在世界 '{world_name}' 中"

   # invalid-world supports placeholder {world_name}
   invalid-world: "§c世界 '{world_name}' 不存在或未加载"

   # only for when this plugin is used from console and no world name is provided
   console-no-world-provided: "请同时提供世界名称"

   # The text that will show up in the bar on the top of the screen in apocalyptic worlds
   apocalypse-boss-bar-title: "§5僵尸末日正在进行中！"

   # sent when a player tries to sleep and `allow-sleep` (see above) is set to false.
   no-apocalypse-sleep: "§7这太容易了..."

   # also used when a custom spawner is given!
   # given-zombie-egg supports placeholder {item_name} for the name of the egg just received
   given-zombie-egg: "§7您已获得 §r§6{item_name} §7的蛋！"

   # also used when a custom spawner type is incorrect!
   # invalid-egg-type supports placeholder {input} for the users faulty zombie type input
   invalid-egg-type: "§c该僵尸类型不存在！"
```

## Traditional Chinese
```
messages:
   no-command-permission: "§4§l抱歉§r§7，您沒有權限執行此操作！"

   # started-success supports placeholder {world_name}
   started-success: "§a世界 '{world_name}' 成功啟動了末日！"
   # started-broadcast supports placeholder {world_name}
   started-broadcast: "§d僵屍末日已經開始了！"
   # started-failed supports placeholder {world_name}
   start-failed: "§c'{world_name}' 已經開始了末日"
   # started-failed supports placeholder {input}, for the users faulty duration input
   start-invalid-duration: "§c末日持續時間必須是整數！"

   # ended-success supports placeholder {world_name}
   ended-success: "§a世界 '{world_name}' 的末日已經結束了！"
   # ended-failed supports placeholder {world_name}
   end-failed: "§c'{world_name}' 中沒有末日"
   # ended-broadcast supports placeholder {world_name}
   ended-broadcast: "§d這個世界的僵屍末日已經結束了，你現在安全了（暫時）！"
   
   reload-success: "§a插件已成功重新加載！"
   reload-fail: "§c重新加載配置文件失敗！請查看控製臺以獲取更多詳細信息。"
   
   mobcap-too-few-arguments: "§c請同時提供世界名稱和所需的生物群系上限！"
   # supports placeholder {input} for the invalid user input
   mobcap-invalid-amount: "§c請（也）提供生物群系上限為整數"
   # supports placeholder {world_name}
   mobcap-no-apocalypse: "§7'{world_name}' 中沒有 §4僵屍末日§2"
   # supports placeholders {world_name} and {mobcap} for the new mob cap
   mobcap-success: "§a將每個區塊的最大僵屍生成數設置為 {mobcap} 在世界 '{world_name}' 中"

   # invalid-world supports placeholder {world_name}
   invalid-world: "§c世界 '{world_name}' 不存在或未加載"

   # only for when this plugin is used from console and no world name is provided
   console-no-world-provided: "請同時提供世界名稱"

   # The text that will show up in the bar on the top of the screen in apocalyptic worlds
   apocalypse-boss-bar-title: "§5僵屍末日正在進行中！"

   # sent when a player tries to sleep and `allow-sleep` (see above) is set to false.
   no-apocalypse-sleep: "§7這太容易了..."

   # also used when a custom spawner is given!
   # given-zombie-egg supports placeholder {item_name} for the name of the egg just received
   given-zombie-egg: "§7您已獲得 §r§6{item_name} §7的蛋！"

   # also used when a custom spawner type is incorrect!
   # invalid-egg-type supports placeholder {input} for the users faulty zombie type input
   invalid-egg-type: "§c該僵屍類型不存在！"
```

## Czech
```
messages:
   no-command-permission: "§4§lOmlouváme se§r§7, nemáte oprávnění k tomu!"

   # started-success supports placeholder {world_name}
   started-success: "§aApocalyse úspěšně spuštěna v '{world_name}'!"
   # started-broadcast supports placeholder {world_name}
   started-broadcast: "§dZombie apokalypsa právě začala!"
   # started-failed supports placeholder {world_name}
   start-failed: "§cApokalypsa již začala v '{world_name}'"
   # started-failed supports placeholder {input}, for the users faulty duration input
   start-invalid-duration: "§cMinuty, po které by měla apokalypsa trvat, musí být celé číslo!"

   # ended-success supports placeholder {world_name}
   ended-success: "§aApokalypsa skončila ve světě: '{world_name}'!"
   # ended-failed supports placeholder {world_name}
   end-failed: "§cV '{world_name}' není žádná apokalypsa'" 
   # ended-broadcast supports placeholder {world_name}
   ended-broadcast: "§dZombie apokalypsa v tomto světě skončila, jste v bezpečí (prozatím)!"
   
   reload-success: "§aPlugin byl úspěšně znovu načten!"
   reload-fail: "§cZnovunačtení konfigurace selhalo! Podívejte se do konzole pro více informací."
   
   mobcap-too-few-arguments: "§cProsím, zadejte také název světa a požadovaný mobcap!"
   # supports placeholder {input} for the invalid user input
   mobcap-invalid-amount: "§cProsím, zadejte mob cap také jako celé číslo"
   # supports placeholder {world_name}
   mobcap-no-apocalypse: "§7V '{world_name}' není §4Zombie§2Apokalypsa§7"
   # supports placeholders {world_name} and {mobcap} for the new mob cap
   mobcap-success: "§aNastavil jsem maximální počet zombie spawnů na chunk na {mobcap} ve světě '{world_name}'"

   # invalid-world supports placeholder {world_name}
   invalid-world: "§cSvět '{world_name}' neexistuje nebo není načten"

   # only for when this plugin is used from console and no world name is provided
   console-no-world-provided: "Prosím, zadejte také název světa"

   # The text that will show up in the bar on the top of the screen in apocalyptic worlds
   apocalypse-boss-bar-title: "§5Zombie apokalypsa probíhá!"

   # sent when a player tries to sleep and `allow-sleep` (see above) is set to false.
   no-apocalypse-sleep: "§7To by bylo trochu snadné..."

   # also used when a custom spawner is given!
   # given-zombie-egg supports placeholder {item_name} for the name of the egg just received
   given-zombie-egg: "§7Dostal jste §r§6{item_name}"

   # also used when a custom spawner type is incorrect!
   # invalid-egg-type supports placeholder {input} for the users faulty zombie type input
   invalid-egg-type: "§cTento typ zombie neexistuje!"
```

## French
```
messages:
   no-command-permission: "§4§lDésolé§r§7, vous n'avez pas la permission pour cela!"

   # started-success supports placeholder {world_name}
   started-success: "§aApocalyse a commencé avec succès dans '{world_name}'!"
   # started-broadcast supports placeholder {world_name}
   started-broadcast: "§dL'apocalypse zombie vient de commencer!"
   # started-failed supports placeholder {world_name}
   start-failed: "§cL'apocalypse a déjà commencé dans '{world_name}'"
   # started-failed supports placeholder {input}, for the users faulty duration input
   start-invalid-duration: "§cLes minutes pendant lesquelles l'apocalypse doit durer doivent être un entier!"

   # ended-success supports placeholder {world_name}
   ended-success: "§aApocalypse terminée dans le monde: '{world_name}'!"
   # ended-failed supports placeholder {world_name}
   end-failed: "§cIl n'y a pas d'apocalypse dans '{world_name}'" 
   # ended-broadcast supports placeholder {world_name}
   ended-broadcast: "§dL'apocalypse zombie a pris fin dans ce monde, vous êtes en sécurité (pour l'instant)!"
   
   reload-success: "§aLe plugin a été rechargé avec succès!"
   reload-fail: "§cLe rechargement de la configuration a échoué! Voir la console pour plus de détails."
   
   mobcap-too-few-arguments: "§cVeuillez également fournir le nom du monde et le mobcap souhaité!"
   # supports placeholder {input} for the invalid user input
   mobcap-invalid-amount: "§cVeuillez (également) fournir le mob cap en tant qu'entier"
   # supports placeholder {world_name}
   mobcap-no-apocalypse: "§7Il n'y a pas d'§4Apocalypse§2Zombie§7 dans le monde '{world_name}'"
   # supports placeholders {world_name} and {mobcap} for the new mob cap
   mobcap-success: "§aDéfinir le nombre maximum de zombies apparus par chunk à {mobcap} dans le monde '{world_name}'"

   # invalid-world supports placeholder {world_name}
   invalid-world: "§cLe monde '{world_name}' n'existe pas ou n'est pas chargé"

   # only for when this plugin is used from console and no world name is provided
   console-no-world-provided: "Veuillez également fournir le nom du monde"

   # The text that will show up in the bar on the top of the screen in apocalyptic worlds
   apocalypse-boss-bar-title: "§5Apocalypse zombie en cours!"

   # sent when a player tries to sleep and `allow-sleep` (see above) is set to false.
   no-apocalypse-sleep: "§7Ce serait un peu trop facile..."

   # also used when a custom spawner is given!
   # given-zombie-egg supports placeholder {item_name} for the name of the egg just received
   given-zombie-egg: "§7Vous avez reçu un §r§6{item_name}"

   # also used when a custom spawner type is incorrect!
   # invalid-egg-type supports placeholder {input} for the users faulty zombie type input
   invalid-egg-type: "§cCe type de zombie n'existe pas!"
```

## Russian
```
messages:
   no-command-permission: "§4§lИзвините§r§7, у вас нет разрешения на это!"

   # started-success supports placeholder {world_name}
   started-success: "§aApocalyse успешно запущен в '{world_name}'!"
   # started-broadcast supports placeholder {world_name}
   started-broadcast: "§dЗомби-апокалипсис только что начался!"
   # started-failed supports placeholder {world_name}
   start-failed: "§cАпокалипсис уже начался в '{world_name}'"
   # started-failed supports placeholder {input}, for the users faulty duration input
   start-invalid-duration: "§cМинуты, на которые должен длиться апокалипсис, должны быть целым числом!"

   # ended-success supports placeholder {world_name}
   ended-success: "§aАпокалипсис закончился в мире: '{world_name}'!"
   # ended-failed supports placeholder {world_name}
   end-failed: "§cВ '{world_name}' нет апокалипсиса" 
   # ended-broadcast supports placeholder {world_name}
   ended-broadcast: "§dЗомби-апокалипсис закончился в этом мире, вы в безопасности (пока)!"
   
   reload-success: "§aПлагин успешно перезагружен!"
   reload-fail: "§cПерезагрузка конфигурации не удалась! Смотрите консоль для получения дополнительной информации."
   
   mobcap-too-few-arguments: "§cПожалуйста, укажите также имя мира и желаемый мобкап!"
   # supports placeholder {input} for the invalid user input
   mobcap-invalid-amount: "§cПожалуйста, (также) укажите максимальное количество мобов в виде целого числа"
   # supports placeholder {world_name}
   mobcap-no-apocalypse: "§7В мире '{world_name}' нет §4Zombie§2Apocalypse§7"
   # supports placeholders {world_name} and {mobcap} for the new mob cap
   mobcap-success: "§aУстановлен максимальный спавн зомби на чанк в {mobcap} в мире '{world_name}'"

   # invalid-world supports placeholder {world_name}
   invalid-world: "§cМир '{world_name}' не существует или не загружен"

   # only for when this plugin is used from console and no world name is provided
   console-no-world-provided: "Пожалуйста, укажите также имя мира"

   # The text that will show up in the bar on the top of the screen in apocalyptic worlds
   apocalypse-boss-bar-title: "§5Зомби-апокалипсис продолжается!"

   # sent when a player tries to sleep and `allow-sleep` (see above) is set to false.
   no-apocalypse-sleep: "§7Это было бы слишком легко..."

   # also used when a custom spawner is given!
   # given-zombie-egg supports placeholder {item_name} for the name of the egg just received
   given-zombie-egg: "§7Вам было дано яйцо §r§6{item_name}"

   # also used when a custom spawner type is incorrect!
   # invalid-egg-type supports placeholder {input} for the users faulty zombie type input
   invalid-egg-type: "§cТакой тип зомби не существует!"
```

## Spanish
```
mensajes:
   no-command-permission: "§4§lLo siento§r§7, no tienes permiso para eso!"

   # started-success supports placeholder {world_name}
   started-success: "§aApocalyse iniciado con éxito en '{world_name}'!"
   # started-broadcast supports placeholder {world_name}
   started-broadcast: "§d¡El apocalipsis zombie acaba de comenzar!"
   # started-failed supports placeholder {world_name}
   start-failed: "§cEl apocalipsis ya ha comenzado en '{world_name}'"
   # started-failed supports placeholder {input}, for the users faulty duration input
   start-invalid-duration: "§c¡Los minutos que debe durar el apocalipsis deben ser un número entero!"

   # ended-success supports placeholder {world_name}
   ended-success: "§a¡El apocalipsis ha terminado en el mundo: '{world_name}'!"
   # ended-failed supports placeholder {world_name}
   end-failed: "§cNo hay apocalipsis en '{world_name}'" 
   # ended-broadcast supports placeholder {world_name}
   ended-broadcast: "§dEl apocalipsis zombie ha terminado en este mundo, estás a salvo (por ahora)!"
   
   reload-success: "§a¡El complemento se ha recargado correctamente!"
   reload-fail: "§c¡Error al recargar la configuración! Consulte la consola para obtener más detalles."
   
   mobcap-too-few-arguments: "§cPor favor, proporcione también el nombre del mundo y el límite de mobs deseado."
   # supports placeholder {input} for the invalid user input
   mobcap-invalid-amount: "§cPor favor, proporcione (también) el límite de mobs como un número entero."
   # supports placeholder {world_name}
   mobcap-no-apocalypse: "§7No hay §4Apocalipsis§2Zombie§7 en el mundo '{world_name}'"
   # supports placeholders {world_name} and {mobcap} for the new mob cap
   mobcap-success: "§aSe ha establecido el máximo de zombies por trozo en {mobcap} en el mundo '{world_name}'"

   # invalid-world supports placeholder {world_name}
   invalid-world: "§cEl mundo '{world_name}' no existe o no está cargado."

   # only for when this plugin is used from console and no world name is provided
   console-no-world-provided: "Por favor, proporcione también el nombre del mundo."

   # The text that will show up in the bar on the top of the screen in apocalyptic worlds
   apocalypse-boss-bar-title: "§5¡Apocalipsis zombie en curso!"

   # sent when a player tries to sleep and `allow-sleep` (see above) is set to false.
   no-apocalypse-sleep: "§7Eso sería un poco demasiado fácil..."

   # also used when a custom spawner is given!
   # given-zombie-egg supports placeholder {item_name} for the name of the egg just received
   given-zombie-egg: "§7Se le ha dado un §r§6{item_name}"

   # also used when a custom spawner type is incorrect!
   # invalid-egg-type supports placeholder {input} for the users faulty zombie type input
   invalid-egg-type: "§c¡Ese tipo de zombie no existe!"
```
